#!/usr/bin/env php
<?php
/**
 * WP Groove™ {@see https://wpgroove.com}
 *  _       _  ___       ___
 * ( )  _  ( )(  _`\    (  _`\
 * | | ( ) | || |_) )   | ( (_) _ __   _      _    _   _    __  ™
 * | | | | | || ,__/'   | |___ ( '__)/'_`\  /'_`\ ( ) ( ) /'__`\
 * | (_/ \_) || |       | (_, )| |  ( (_) )( (_) )| \_/ |(  ___/
 * `\___x___/'(_)       (____/'(_)  `\___/'`\___/'`\___/'`\____)
 */
// <editor-fold desc="Strict types, namespace, use statements, and other headers.">

/**
 * Declarations & namespace.
 *
 * @since 2021-12-25
 */
declare( strict_types = 1 ); // ｡･:*:･ﾟ★.
namespace WP_Groove\Framework\Dev\CLI_Tools\I18n;

/**
 * Utilities.
 *
 * @since 2021-12-15
 */
use Clever_Canyon\{Utilities as U};
use Clever_Canyon\Utilities\Dev\{Utilities as D};

/**
 * Framework.
 *
 * @since 2021-12-15
 */
use WP_Groove\{Framework as WPG};

// </editor-fold>

/**
 * CLI mode only.
 *
 * @since 2021-12-15
 */
if ( 'cli' !== PHP_SAPI ) {
	exit( 1 ); // CLI mode only.
}

/**
 * Requires dev utilities.
 *
 * @since 2021-12-15
 */
if ( is_dir( dirname( __FILE__, 4 ) . '/vendor' ) ) { // Possible symlink. That's OK here.
	require_once dirname( __FILE__, 4 ) . '/vendor/clevercanyon/php-js-utilities/dev/utilities/load.php';
} else { // Assume running as a dependency from inside of another project’s `/vendor` directory.
	require_once dirname( __FILE__, 7 ) . '/vendor/clevercanyon/php-js-utilities/dev/utilities/load.php';
}

/**
 * Requires autoloader.
 *
 * @since 2021-12-15
 */
require_once D\Dir::join( D\CLI::project_dir(), '/vendor/autoload.php' );

/**
 * Enables debugging mode.
 *
 * @since 2021-12-15
 */
U\Env::config_debugging_mode();

/**
 * CLI tool instance.
 *
 * @since 2021-12-15
 */
new WPG\Dev\CLI_Tools\I18n\Text_Domain();
