#!/usr/bin/env php
<?php
/**
 * WP Groove™ {@see https://wpgroove.com}
 *  _       _  ___       ___
 * ( )  _  ( )(  _`\    (  _`\
 * | | ( ) | || |_) )   | ( (_) _ __   _      _    _   _    __  ™
 * | | | | | || ,__/'   | |___ ( '__)/'_`\  /'_`\ ( ) ( ) /'__`\
 * | (_/ \_) || |       | (_, )| |  ( (_) )( (_) )| \_/ |(  ___/
 * `\___x___/'(_)       (____/'(_)  `\___/'`\___/'`\___/'`\____)
 */
// <editor-fold desc="Strict types, namespace, use statements, and other headers.">

/**
 * Declarations & namespace.
 *
 * @since 2021-12-25
 */
declare( strict_types = 1 ); // ｡･:*:･ﾟ★.
namespace WP_Groove\Framework\Dev\CLI_Tools\Composer;

/**
 * Utilities.
 *
 * @since 2021-12-15
 */
use Clever_Canyon\{Utilities as U};

/**
 * Framework.
 *
 * @since 2021-12-15
 */
use WP_Groove\{Framework as WPG};

// </editor-fold>

/**
 * CLI mode only.
 *
 * @since 2021-12-15
 */
if ( 'cli' !== PHP_SAPI ) {
	exit( 1 ); // CLI mode only.
}

/**
 * Dev mode only.
 *
 * @since 2021-12-15
 */
if ( ! getenv( 'COMPOSER_DEV_MODE' ) ) {
	exit( 1 ); // Dev mode only.
}

/**
 * Project directory.
 *
 * @since 2021-12-15
 */
$project_dir = require __DIR__ . '/.cli-project-dir.php';

/**
 * Requires autoloader.
 *
 * @since 2021-12-15
 */
require_once $project_dir . '/vendor/autoload.php';

/**
 * Enables debugging mode.
 *
 * @since 2021-12-15
 */
U\Env::config_debugging_mode();

/**
 * Handles `post-update-cmd` hook.
 *
 * @since 2021-12-15
 */
if ( 'update' === ( $argv[ 1 ] ?? '' ) ) {
	new U\Dev\CLI_Tools\Composer\On_Post_Update_Cmd( [ 'update', '--project-dir', $project_dir ] );
	new WPG\Dev\CLI_Tools\Composer\On_Post_Update_Cmd( [ 'update', '--project-dir', $project_dir ] );
} else {
	new U\Dev\CLI_Tools\Composer\On_Post_Update_Cmd( [ 'symlink', '--project-dir', $project_dir ] );
	U\CLI::run( [ $argv[ 0 ], 'update' ] ); // Separate process, after symlinks.
}
